import type { DashboardData } from "@/types/dashboard";
import type { AdminResources } from "@/types/admin";

export const MOCK_DASHBOARD_DATA: DashboardData = {
  adminName: "Dr. Elena Ramos, MD",
  role: "Barangay Health Physician",
  dateString: "Saturday, October 24, 2026",
  metrics: {
    totalResidents: {
      count: 1420,
      trendText: "+12% this month",
    },
    consultationsToday: {
      count: 18,
      trendText: "+4 today",
    },
    pendingAppointments: {
      count: 12,
      trendText: "3 need review",
    },
    activeBHWs: {
      count: 8,
      statusText: "8 on duty",
    },
  },
  consultationTrend: [
    { day: "Mon", date: "Oct 19", count: 14 },
    { day: "Tue", date: "Oct 20", count: 19 },
    { day: "Wed", date: "Oct 21", count: 24 },
    { day: "Thu", date: "Oct 22", count: 18 },
    { day: "Fri", date: "Oct 23", count: 29 },
    { day: "Sat", date: "Oct 24", count: 16 },
    { day: "Sun", date: "Oct 25", count: 11 },
  ],
  commonSymptoms: {
    totalCases: 128,
    breakdown: [
      { name: "Fever & Chills", percentage: 35, color: "#16a34a" },
      { name: "Cough & Cold", percentage: 28, color: "#3b82f6" },
      { name: "Hypertension / Dizziness", percentage: 18, color: "#f59e0b" },
      { name: "Skin Rash & Allergies", percentage: 12, color: "#ec4899" },
      { name: "Stomach Pain / Diarrhea", percentage: 7, color: "#8b5cf6" },
    ],
  },
  pendingConsultations: [
    {
      id: "c-1",
      initials: "MS",
      residentName: "Maria Santos",
      concern: "Persistent Dry Cough & Fever for 3 days",
      assignedBHW: "Ana Reyes (BHW)",
      status: "Waiting",
      caseNumber: "CAS-2026-0481",
      gender: "Female",
      age: 34,
      phone: "0917-123-4567",
      purok: "Purok 2",
      timeAgo: "10 mins ago",
      createdDate: "Oct 24, 2026 • 09:30 AM",
      priority: "High",
      chiefComplaint: "High fever (38.8°C) accompanied by dry cough and mild chest soreness for 3 consecutive days.",
      symptoms: ["Fever (38.8°C)", "Dry Cough", "Headache", "Body Malaise"],
      additionalNotes: "Resident has history of mild bronchial asthma. Took Paracetamol 500mg 4 hours ago with temporary relief.",
      bhwDetails: {
        name: "Ana Reyes (BHW)",
        role: "Purok 2 Health Worker",
        phone: "0928-123-4567",
        avatar: "/assets/female-doctor.webp",
      },
      conversation: [
        {
          id: "m-1",
          sender: "resident",
          senderName: "Maria Santos",
          text: "Magandang umaga po BHW Ana. May mataas na lagnat po ako simula pa noong Miyerkules at tuyong ubo.",
          timestamp: "09:30 AM",
        },
        {
          id: "m-2",
          sender: "bhw",
          senderName: "Ana Reyes (BHW)",
          text: "Magandang umaga Ma'am Maria. Na-check niyo po ba ang inyong temperatura gamit ang thermometer kanina?",
          timestamp: "09:35 AM",
        },
        {
          id: "m-3",
          sender: "resident",
          senderName: "Maria Santos",
          text: "Opo, 38.8°C po kaninang 8 AM. Uminom na po ako ng Paracetamol pero bumabalik po.",
          timestamp: "09:40 AM",
        },
      ],
    },
    {
      id: "c-2",
      initials: "JD",
      residentName: "Juan Dela Cruz",
      concern: "Blood Pressure Spike (150/95 mmHg)",
      assignedBHW: "Marites Dela Cruz (BHW)",
      status: "Active",
      caseNumber: "CAS-2026-0482",
      gender: "Male",
      age: 58,
      phone: "0920-555-7890",
      purok: "Purok 1",
      timeAgo: "25 mins ago",
      createdDate: "Oct 24, 2026 • 09:15 AM",
      priority: "Urgent",
      chiefComplaint: "Occipital headache and dizziness upon waking up. Home BP cuff reads 150/95 mmHg.",
      symptoms: ["Elevated BP (150/95)", "Dizziness", "Neck Stiff"],
      additionalNotes: "Diagnosed hypertensive on maintenance Amlodipine 5mg. Missed yesterday's dosage.",
      bhwDetails: {
        name: "Marites Dela Cruz (BHW)",
        role: "Purok 1 Health Worker",
        phone: "0919-444-1122",
        avatar: "/assets/female-doctor.webp",
      },
      conversation: [
        {
          id: "m-201",
          sender: "resident",
          senderName: "Juan Dela Cruz",
          text: "Naninikip po ang batok ko at nahihilo. 150/95 ang BP ko ngayon.",
          timestamp: "09:15 AM",
        },
        {
          id: "m-202",
          sender: "bhw",
          senderName: "Marites Dela Cruz (BHW)",
          text: "Tatay Juan, umupo muna po at magpahinga. Huwag munang magpagod. Pupuntahan ko po kayo sa bahay kasama ang clinic BP apparatus.",
          timestamp: "09:20 AM",
        },
      ],
    },
    {
      id: "c-3",
      initials: "RM",
      residentName: "Rosa Mendoza",
      concern: "Pediatric Rashes & Itching (Baby Sofia, 2yo)",
      assignedBHW: "Ana Reyes (BHW)",
      status: "Replied",
      caseNumber: "CAS-2026-0483",
      gender: "Female",
      age: 28,
      phone: "0918-777-3321",
      purok: "Purok 3",
      timeAgo: "45 mins ago",
      createdDate: "Oct 24, 2026 • 08:55 AM",
      priority: "Medium",
      chiefComplaint: "Red erythematous maculopapular rash on toddler's arms and torso after eating eggs.",
      symptoms: ["Skin Itchiness", "Red Welts", "Mild Irritability"],
      additionalNotes: "No breathing difficulty or wheezing observed. Child is active and hydrated.",
      bhwDetails: {
        name: "Ana Reyes (BHW)",
        role: "Purok 2 Health Worker",
        phone: "0928-123-4567",
        avatar: "/assets/female-doctor.webp",
      },
      conversation: [
        {
          id: "m-301",
          sender: "resident",
          senderName: "Rosa Mendoza",
          text: "Nagkaroon po ng mga pantal ang anak kong 2 years old pagkakain ng scrambled egg.",
          timestamp: "08:55 AM",
        },
        {
          id: "m-302",
          sender: "bhw",
          senderName: "Ana Reyes (BHW)",
          text: "Inirekumenda po ni Dra. Ramos na bigyan ng Cetirizine drops ayon sa timbang ng bata. May libreng stock po sa clinic kung nais niyong daanan.",
          timestamp: "09:05 AM",
        },
      ],
    },
    {
      id: "c-4",
      initials: "RG",
      residentName: "Ricardo Gomez",
      concern: "Maintenance Medicine Refill - Losartan 50mg",
      assignedBHW: "Elena Cruz (BHW)",
      status: "Waiting",
      caseNumber: "CAS-2026-0484",
      gender: "Male",
      age: 64,
      phone: "0921-888-9900",
      purok: "Purok 4",
      timeAgo: "1 hour ago",
      createdDate: "Oct 24, 2026 • 08:30 AM",
      priority: "Low",
      chiefComplaint: "Requesting 1-month maintenance allotment for Losartan Potassium 50mg with Senior Citizen Booklet.",
      symptoms: ["None - Routine Maintenance Refill"],
      additionalNotes: "Senior ID: SN-2021-9942. Last BP check: 124/82 mmHg.",
      bhwDetails: {
        name: "Elena Cruz (BHW)",
        role: "Purok 4 Health Worker",
        phone: "0922-333-8899",
        avatar: "/assets/female-doctor.webp",
      },
      conversation: [
        {
          id: "m-401",
          sender: "resident",
          senderName: "Ricardo Gomez",
          text: "Hello po, magpaparefill lang po ako ng Losartan maintenance ko para sa susunod na buwan.",
          timestamp: "08:30 AM",
        },
      ],
    },
    {
      id: "c-5",
      initials: "TA",
      residentName: "Teresa Aquino",
      concern: "Prenatal Third Trimester Guidance (Week 32)",
      assignedBHW: "Midwife May Castro",
      status: "Active",
      caseNumber: "CAS-2026-0485",
      gender: "Female",
      age: 26,
      phone: "0916-999-4455",
      purok: "Purok 2",
      timeAgo: "2 hours ago",
      createdDate: "Oct 24, 2026 • 07:45 AM",
      priority: "Medium",
      chiefComplaint: "Mild pedal edema and inquiry on upcoming tetanus toxoid booster schedule.",
      symptoms: ["Swollen Ankles", "Backache", "Normal Fetal Movement"],
      additionalNotes: "G1P0, 32 weeks AOG. Normal fundic height. Taking Ferrous Sulfate daily.",
      bhwDetails: {
        name: "Midwife May Castro",
        role: "Barangay Health Midwife",
        phone: "0917-888-2233",
        avatar: "/assets/female-doctor.webp",
      },
      conversation: [
        {
          id: "m-501",
          sender: "resident",
          senderName: "Teresa Aquino",
          text: "Magandang umaga Midwife May! Kailan po ulit ang prenatal checkup at bakuna ko para sa buwan na ito?",
          timestamp: "07:45 AM",
        },
        {
          id: "m-502",
          sender: "bhw",
          senderName: "Midwife May Castro",
          text: "Hello Teresa! Naka-schedule ka sa Martes, 9:00 AM para sa iyong physical exam at ultrasound review.",
          timestamp: "08:05 AM",
        },
      ],
    },
    {
      id: "c-6",
      initials: "JB",
      residentName: "Jose Bautista",
      concern: "Mild Stomach Pain & Acid Reflux",
      assignedBHW: "Ana Reyes (BHW)",
      status: "Completed",
      caseNumber: "CAS-2026-0480",
      gender: "Male",
      age: 42,
      phone: "0927-444-1234",
      purok: "Purok 5",
      timeAgo: "3 hours ago",
      createdDate: "Oct 24, 2026 • 06:50 AM",
      priority: "Low",
      chiefComplaint: "Epigastric burning discomfort after skipping breakfast.",
      symptoms: ["Heartburn", "Bloating"],
      additionalNotes: "Advised antacid (Aluminum Magnesium Hydroxide) and dietary modification.",
      bhwDetails: {
        name: "Ana Reyes (BHW)",
        role: "Purok 2 Health Worker",
        phone: "0928-123-4567",
        avatar: "/assets/female-doctor.webp",
      },
      conversation: [
        {
          id: "m-601",
          sender: "resident",
          senderName: "Jose Bautista",
          text: "Kumusta po, mas maayos na po ang pakiramdam ko pagkatapos uminom ng antacid.",
          timestamp: "07:15 AM",
        },
        {
          id: "m-602",
          sender: "bhw",
          senderName: "Ana Reyes (BHW)",
          text: "Mabuti po kung ganoon Sir Jose. Iwasan muna ang sobrang maanghang at kape ngayong araw.",
          timestamp: "07:20 AM",
        },
      ],
    },
  ],
  upcomingAppointments: [
    {
      id: "apt-1",
      month: "OCT",
      day: "26",
      residentName: "Elena Ramos",
      category: "Prenatal Checkup",
      timeSlot: "09:00 AM - 10:00 AM",
    },
    {
      id: "apt-2",
      month: "OCT",
      day: "26",
      residentName: "Marco Reyes",
      category: "Pediatric Immunization",
      timeSlot: "10:30 AM - 11:30 AM",
    },
    {
      id: "apt-3",
      month: "OCT",
      day: "27",
      residentName: "Lourdes Castillo",
      category: "Senior Wellness & BP Check",
      timeSlot: "01:30 PM - 02:30 PM",
    },
    {
      id: "apt-4",
      month: "OCT",
      day: "28",
      residentName: "Arthur Hernandez",
      category: "Fasting Blood Sugar Test",
      timeSlot: "08:00 AM - 09:00 AM",
    },
    {
      id: "apt-5",
      month: "OCT",
      day: "29",
      residentName: "Clarissa Dizon",
      category: "General Medical Consult",
      timeSlot: "02:00 PM - 03:00 PM",
    },
    {
      id: "apt-6",
      month: "OCT",
      day: "30",
      residentName: "Baby Liam Santiago",
      category: "Pentavalent Vaccine Dose 2",
      timeSlot: "09:30 AM - 10:30 AM",
    },
  ],
  recentActivity: [
    {
      id: "act-1",
      actor: "Dr. Elena Ramos, MD",
      action: "Approved 15 maintenance prescriptions for Senior Hypertension Drive",
      timeAgo: "12 mins ago",
      type: "consultation",
    },
    {
      id: "act-2",
      actor: "BHW Ana Reyes",
      action: "Recorded vital signs and triage intake for Maria Santos (Purok 2)",
      timeAgo: "22 mins ago",
      type: "consultation",
    },
    {
      id: "act-3",
      actor: "Nurse Carmela Perez",
      action: "Updated medicine inventory: Received +500 tablets of Paracetamol 500mg",
      timeAgo: "1 hour ago",
      type: "medicine",
    },
    {
      id: "act-4",
      actor: "Admin Desk",
      action: "Published public health advisory: Free Flu Vaccination Drive this Saturday",
      timeAgo: "2 hours ago",
      type: "announcement",
    },
    {
      id: "act-5",
      actor: "Midwife May Castro",
      action: "Confirmed 6 prenatal checkups for Tuesday clinic hours",
      timeAgo: "3 hours ago",
      type: "appointment",
    },
    {
      id: "act-6",
      actor: "System Audit",
      action: "Nightly synchronization with Pasig City DOH Health Information Network completed",
      timeAgo: "5 hours ago",
      type: "user",
    },
  ],
};

export const MOCK_ADMIN_RESOURCES: AdminResources = {
  appointments: [
    {
      id: "cal-1",
      residentName: "Elena Ramos",
      initials: "ER",
      service: "Prenatal Checkup",
      time: "09:00 AM",
      date: "2026-10-26",
      assignedBhw: "Midwife May Castro",
      status: "Confirmed",
      dotColor: "green",
      notes: "Routine 3rd trimester evaluation",
      contact: "0917-111-2233",
      purok: "Purok 2",
    },
    {
      id: "cal-2",
      residentName: "Marco Reyes",
      initials: "MR",
      service: "Pediatric Immunization",
      time: "10:30 AM",
      date: "2026-10-26",
      assignedBhw: "Nurse Carmela Perez",
      status: "Confirmed",
      dotColor: "blue",
      notes: "Rotavirus & Pentavalent dose",
      contact: "0918-222-3344",
      purok: "Purok 1",
    },
    {
      id: "cal-3",
      residentName: "Lourdes Castillo",
      initials: "LC",
      service: "Senior Wellness & BP Check",
      time: "01:30 PM",
      date: "2026-10-27",
      assignedBhw: "BHW Marites Dela Cruz",
      status: "Confirmed",
      dotColor: "green",
      notes: "Cardiovascular risk appraisal",
      contact: "0919-333-4455",
      purok: "Purok 3",
    },
    {
      id: "cal-4",
      residentName: "Arthur Hernandez",
      initials: "AH",
      service: "Fasting Blood Sugar Test",
      time: "08:00 AM",
      date: "2026-10-28",
      assignedBhw: "Nurse Carmela Perez",
      status: "Pending",
      dotColor: "orange",
      notes: "Needs 10 hours fasting preparation",
      contact: "0920-444-5566",
      purok: "Purok 4",
    },
    {
      id: "cal-5",
      residentName: "Clarissa Dizon",
      initials: "CD",
      service: "General Medical Consult",
      time: "02:00 PM",
      date: "2026-10-29",
      assignedBhw: "Dr. Elena Ramos, MD",
      status: "Confirmed",
      dotColor: "green",
      notes: "Persistent recurring migraines",
      contact: "0921-555-6677",
      purok: "Purok 2",
    },
    {
      id: "cal-6",
      residentName: "Baby Liam Santiago",
      initials: "LS",
      service: "Pentavalent Vaccine Dose 2",
      time: "09:30 AM",
      date: "2026-10-30",
      assignedBhw: "Nurse Carmela Perez",
      status: "Confirmed",
      dotColor: "blue",
      notes: "Bring immunization booklet",
      contact: "0922-666-7788",
      purok: "Purok 5",
    },
    {
      id: "cal-7",
      residentName: "Felipe Vergara",
      initials: "FV",
      service: "Wound Dressing & Dressing Change",
      time: "11:00 AM",
      date: "2026-10-26",
      assignedBhw: "BHW Ana Reyes",
      status: "Walk-in",
      dotColor: "orange",
      notes: "Post-minor surgical abrasion care",
      contact: "0923-777-8899",
      purok: "Purok 1",
    },
    {
      id: "cal-8",
      residentName: "Corazon Aquino",
      initials: "CA",
      service: "Diabetes Lifestyle Follow-up",
      time: "03:30 PM",
      date: "2026-10-27",
      assignedBhw: "Dr. Elena Ramos, MD",
      status: "Confirmed",
      dotColor: "green",
      notes: "Review continuous glucose monitoring log",
      contact: "0924-888-9900",
      purok: "Purok 3",
    },
  ],
  appointmentRequests: [
    {
      id: "req-1",
      residentName: "Arthur Hernandez",
      initials: "AH",
      serviceType: "Fasting Blood Sugar Test",
      preferredTime: "Oct 28, 2026 8:00 AM",
      assignedBhw: "Nurse Carmela Perez",
      status: "Pending",
      avatarBg: "#e0f2fe",
      contact: "0920-444-5566",
      purok: "Purok 4",
    },
    {
      id: "req-2",
      residentName: "Remedios Villanueva",
      initials: "RV",
      serviceType: "Senior Wellness & Eye Examination",
      preferredTime: "Oct 31, 2026 10:00 AM",
      assignedBhw: "BHW Marites Dela Cruz",
      status: "Pending",
      avatarBg: "#fef3c7",
      contact: "0925-999-0011",
      purok: "Purok 2",
    },
    {
      id: "req-3",
      residentName: "Danilo Castro",
      initials: "DC",
      serviceType: "Asthma Controller Prescription Renewal",
      preferredTime: "Nov 02, 2026 1:30 PM",
      assignedBhw: "Dr. Elena Ramos, MD",
      status: "Pending",
      avatarBg: "#fce7f3",
      contact: "0926-111-2244",
      purok: "Purok 3",
    },
    {
      id: "req-4",
      residentName: "Jessica Tan",
      initials: "JT",
      serviceType: "Postnatal Mother & Newborn Care",
      preferredTime: "Nov 03, 2026 9:30 AM",
      assignedBhw: "Midwife May Castro",
      status: "Pending",
      avatarBg: "#dcfce7",
      contact: "0927-222-3355",
      purok: "Purok 1",
    },
  ],
  staffAvailability: [
    {
      id: "bhw-1",
      name: "Ana Reyes (BHW)",
      activeSlots: 6,
      totalSlots: 8,
      percentage: 75,
      status: "available",
    },
    {
      id: "bhw-2",
      name: "Marites Dela Cruz (BHW)",
      activeSlots: 8,
      totalSlots: 8,
      percentage: 100,
      status: "busy",
    },
    {
      id: "bhw-3",
      name: "Carmela Perez (Nurse)",
      activeSlots: 5,
      totalSlots: 8,
      percentage: 62,
      status: "available",
    },
    {
      id: "bhw-4",
      name: "May Castro (Midwife)",
      activeSlots: 4,
      totalSlots: 8,
      percentage: 50,
      status: "available",
    },
  ],
  medicines: [
    {
      id: "med-1",
      name: "Paracetamol",
      genericName: "Acetaminophen",
      category: "Fever & Pain",
      use: "First-line antipyretic and analgesic for fever, headache, body malaise, and mild to moderate pain.",
      dosage: "500 mg",
      adultDosage: "1-2 tablets every 4-6 hours as needed (Max 4,000 mg/day).",
      pediatricDosage: "10-15 mg/kg body weight per dose (Use pediatric syrup formulation).",
      stockStatus: "In Stock",
      stockQuantity: 450,
      updatedBy: "Nurse Carmela Perez",
      updatedDate: "Today, 10:15 AM",
      caution: "Do not exceed maximum daily dosage to prevent hepatic toxicity. Avoid concurrent alcohol consumption.",
      symptomTags: ["Fever", "Headache", "Body Pain", "Toothache"],
      imageType: "tablet",
      isActive: true,
    },
    {
      id: "med-2",
      name: "Amoxicillin",
      genericName: "Amoxicillin Trihydrate",
      category: "Antibiotic",
      use: "Broad-spectrum penicillin antibiotic for bacterial respiratory, ear, throat, and skin infections.",
      dosage: "500 mg",
      adultDosage: "1 capsule every 8 hours for 7 full days as prescribed by a licensed physician.",
      pediatricDosage: "25-50 mg/kg/day divided every 8 hours (Syrup formulation).",
      stockStatus: "In Stock",
      stockQuantity: 280,
      updatedBy: "Nurse Carmela Perez",
      updatedDate: "Yesterday, 02:30 PM",
      caution: "Requires valid doctor's prescription. Finish the entire course even if symptoms resolve.",
      symptomTags: ["Bacterial Infection", "Tonsillitis", "Pneumonia", "Ear Pain"],
      imageType: "capsule",
      isActive: true,
    },
    {
      id: "med-3",
      name: "Cetirizine",
      genericName: "Cetirizine Dihydrochloride",
      category: "Allergy",
      use: "Second-generation antihistamine for allergic rhinitis, urticaria, pruritus, and insect bites.",
      dosage: "10 mg",
      adultDosage: "1 tablet once daily at bedtime.",
      pediatricDosage: "2.5 mg to 5 mg once daily based on age.",
      stockStatus: "In Stock",
      stockQuantity: 190,
      updatedBy: "BHW Ana Reyes",
      updatedDate: "Oct 22, 2026",
      caution: "May cause mild drowsiness in sensitive individuals. Avoid operating heavy machinery.",
      symptomTags: ["Allergies", "Sneezing", "Skin Rashes", "Itchy Eyes"],
      imageType: "tablet",
      isActive: true,
    },
    {
      id: "med-4",
      name: "Losartan Potassium",
      genericName: "Losartan",
      category: "Hypertension",
      use: "Angiotensin II receptor blocker (ARB) for essential hypertension and nephropathy protection.",
      dosage: "50 mg",
      adultDosage: "1 tablet once daily in the morning.",
      pediatricDosage: "Not indicated for pediatric community distribution without specialist advice.",
      stockStatus: "Low Stock",
      stockQuantity: 42,
      updatedBy: "Dr. Elena Ramos, MD",
      updatedDate: "Oct 23, 2026",
      caution: "Contraindicated in pregnancy. Regular blood pressure monitoring is required.",
      symptomTags: ["High Blood Pressure", "Hypertension", "Cardiovascular Care"],
      imageType: "tablet",
      isActive: true,
    },
    {
      id: "med-5",
      name: "Metformin Hydrochloride",
      genericName: "Metformin",
      category: "Supplements",
      use: "Biguanide antihyperglycemic agent for management of Type 2 Diabetes Mellitus.",
      dosage: "500 mg",
      adultDosage: "1 tablet twice daily with meals to minimize gastrointestinal side effects.",
      pediatricDosage: "Requires endocrinologist referral.",
      stockStatus: "In Stock",
      stockQuantity: 310,
      updatedBy: "Dr. Elena Ramos, MD",
      updatedDate: "Oct 21, 2026",
      caution: "Take with or immediately after food. Monitor renal function periodically.",
      symptomTags: ["Diabetes", "Blood Sugar", "Metabolic Health"],
      imageType: "tablet",
      isActive: true,
    },
    {
      id: "med-6",
      name: "Oral Rehydration Salts (ORS)",
      genericName: "WHO Standard Formulation",
      category: "Hydration",
      use: "Restoration of fluid and electrolyte depletion in acute diarrhea, gastroenteritis, and heat exhaustion.",
      dosage: "1 Sachet / 1 Liter Water",
      adultDosage: "Drink 200-400 mL after each loose stool.",
      pediatricDosage: "50-100 mL after each loose stool for infants and young children.",
      stockStatus: "In Stock",
      stockQuantity: 520,
      updatedBy: "BHW Ana Reyes",
      updatedDate: "Today, 08:00 AM",
      caution: "Mix only with clean drinking water. Discard any unused reconstituted solution after 24 hours.",
      symptomTags: ["Diarrhea", "Dehydration", "Vomiting", "Heat Exhaustion"],
      imageType: "sachet",
      isActive: true,
    },
    {
      id: "med-7",
      name: "Salbutamol Inhaler",
      genericName: "Albuterol Sulfate",
      category: "Cough & Cold",
      use: "Short-acting beta-2 agonist for relief of acute bronchospasm in asthma and COPD.",
      dosage: "100 mcg/puff",
      adultDosage: "1-2 puffs as needed every 4-6 hours for acute shortness of breath.",
      pediatricDosage: "1-2 puffs using spacer chamber under adult supervision.",
      stockStatus: "Low Stock",
      stockQuantity: 18,
      updatedBy: "Dr. Elena Ramos, MD",
      updatedDate: "Oct 20, 2026",
      caution: "Seek immediate emergency clinic care if inhaler fails to relieve acute respiratory distress.",
      symptomTags: ["Asthma", "Wheezing", "Shortness of Breath", "Bronchospasm"],
      imageType: "capsule",
      isActive: true,
    },
    {
      id: "med-8",
      name: "Ascorbic Acid + Zinc",
      genericName: "Vitamin C + Zinc Sulfate",
      category: "Supplements",
      use: "Daily immune booster and nutritional support during viral infection recovery.",
      dosage: "500 mg / 10 mg",
      adultDosage: "1 capsule once daily after meals.",
      pediatricDosage: "Syrup formulation available at the BHW desk.",
      stockStatus: "In Stock",
      stockQuantity: 620,
      updatedBy: "Nurse Carmela Perez",
      updatedDate: "Oct 22, 2026",
      caution: "Take with water after meals to prevent gastric irritation in hyperacidic patients.",
      symptomTags: ["Immune Support", "Vitamins", "Recovery", "Vitality"],
      imageType: "capsule",
      isActive: true,
    },
    {
      id: "med-9",
      name: "Mefenamic Acid",
      genericName: "Mefenamic Acid",
      category: "Fever & Pain",
      use: "Non-steroidal anti-inflammatory drug (NSAID) for dental pain, dysmenorrhea, and inflammatory conditions.",
      dosage: "500 mg",
      adultDosage: "1 tablet every 8 hours as needed after meals. Short-term use (max 7 days).",
      pediatricDosage: "Not recommended for children under 14 without specialist prescription.",
      stockStatus: "In Stock",
      stockQuantity: 240,
      updatedBy: "Nurse Carmela Perez",
      updatedDate: "Oct 19, 2026",
      caution: "Always take with food or milk. Contraindicated in active peptic ulcer disease.",
      symptomTags: ["Toothache", "Menstrual Cramps", "Joint Inflammation"],
      imageType: "capsule",
      isActive: true,
    },
    {
      id: "med-10",
      name: "Lagundi Tablet",
      genericName: "Vitex Negundo L.",
      category: "Cough & Cold",
      use: "Herbal botanical medicine formulated for acute productive cough and mild asthma symptom relief.",
      dosage: "600 mg",
      adultDosage: "1 tablet 3 to 4 times a day.",
      pediatricDosage: "Use Lagundi pediatric syrup for ages 2 to 12.",
      stockStatus: "In Stock",
      stockQuantity: 340,
      updatedBy: "BHW Ana Reyes",
      updatedDate: "Oct 23, 2026",
      caution: "Consult clinic physician if cough persists for more than 7 days.",
      symptomTags: ["Cough with Phlegm", "Bronchitis", "Herbal Medicine"],
      imageType: "tablet",
      isActive: true,
    },
    {
      id: "med-11",
      name: "Cefalexin",
      genericName: "Cephalexin Monohydrate",
      category: "Antibiotic",
      use: "First-generation cephalosporin for skin, soft tissue, and urinary tract infections.",
      dosage: "500 mg",
      adultDosage: "1 capsule every 6 hours for 7 days.",
      pediatricDosage: "25-50 mg/kg/day divided into 4 doses.",
      stockStatus: "In Stock",
      stockQuantity: 160,
      updatedBy: "Dr. Elena Ramos, MD",
      updatedDate: "Oct 18, 2026",
      caution: "Strictly prescription only. Complete the entire prescribed duration.",
      symptomTags: ["Skin Infection", "Boil", "Cellulitis", "UTI"],
      imageType: "capsule",
      isActive: true,
    },
    {
      id: "med-12",
      name: "Ferrous Sulfate + Folic Acid",
      genericName: "Iron + Folic Acid",
      category: "Supplements",
      use: "Prevention and treatment of iron deficiency anemia in pregnant and lactating mothers.",
      dosage: "60 mg Elemental Iron / 400 mcg Folic Acid",
      adultDosage: "1 tablet once daily on an empty stomach or with citrus juice.",
      pediatricDosage: "Use pediatric iron drops.",
      stockStatus: "In Stock",
      stockQuantity: 480,
      updatedBy: "Midwife May Castro",
      updatedDate: "Today, 09:00 AM",
      caution: "May cause harmless dark stools. Avoid taking with tea, coffee, or calcium supplements.",
      symptomTags: ["Prenatal Care", "Anemia", "Maternal Health", "Folic Acid"],
      imageType: "tablet",
      isActive: true,
    },
  ],
  announcements: [
    {
      id: "anc-1",
      title: "Free Dengue & Quadrivalent Flu Vaccination Drive",
      content: "The Barangay Health Station in partnership with Pasig City Health Department will conduct a community immunization drive this coming Saturday at the Barangay Covered Court from 8:00 AM to 4:00 PM. Open to all registered residents.",
      category: "Vaccination Drive",
      priority: "Important",
      status: "Published",
      targetAudience: "All Barangays",
      broadcastChannels: ["Push Notification", "SMS Sync", "Barangay Bulletin"],
      author: "Dr. Elena Ramos, MD",
      publishedDate: "October 23, 2026",
      reachCount: 1240,
    },
    {
      id: "anc-2",
      title: "Senior Citizen Monthly Maintenance Medicine Distribution",
      content: "All registered senior citizens (Purok 1 to 5) may claim their free 30-day supply of Losartan, Amlodipine, and Metformin starting Monday at the Clinic Pharmacy Desk. Please bring your Senior OSCA ID and pink medical booklet.",
      category: "Health Advisory",
      priority: "Important",
      status: "Published",
      targetAudience: "Senior Citizens",
      broadcastChannels: ["SMS Sync", "Barangay Bulletin"],
      author: "Nurse Carmela Perez",
      publishedDate: "October 22, 2026",
      reachCount: 890,
    },
    {
      id: "anc-3",
      title: "Oplan Linis: Community Dengue Misting & Clean-Up Drive",
      content: "Due to intermittent rains, the BHW Sanitary Committee will conduct 4 o'clock search-and-destroy habitat clearance in Purok 3 and Purok 4. Residents are requested to empty stagnant containers and water basins.",
      category: "Emergency Alert",
      priority: "Urgent",
      status: "Published",
      targetAudience: "Purok 1-3",
      broadcastChannels: ["Push Notification", "SMS Sync", "Barangay Bulletin"],
      author: "BHW Coordinator Ana Reyes",
      publishedDate: "October 21, 2026",
      reachCount: 750,
    },
    {
      id: "anc-4",
      title: "Barangay Maternal & Infant Nutrition Month Feeding Program",
      content: "Supplementary feeding and growth monitoring (Timbang at Tangkad) for children ages 6 months to 5 years. Free fortified cereal and multi-vitamins will be distributed to mothers attending the session.",
      category: "Medical Mission",
      priority: "Normal",
      status: "Published",
      targetAudience: "Mothers & Infants",
      broadcastChannels: ["Push Notification", "Barangay Bulletin"],
      author: "Midwife May Castro",
      publishedDate: "October 19, 2026",
      reachCount: 620,
    },
    {
      id: "anc-5",
      title: "Typhoon Preparedness: 24/7 Clinic Emergency Hotlines",
      content: "In anticipation of the forecasted tropical depression, our 24/7 emergency dispatch numbers are on full alert: Clinic Desk: (02) 8911-0000 | Ambulance: 0928-765-4321. Stay safe and prepared.",
      category: "Emergency Alert",
      priority: "Urgent",
      status: "Published",
      targetAudience: "All Barangays",
      broadcastChannels: ["Push Notification", "SMS Sync", "Barangay Bulletin"],
      author: "Dr. Elena Ramos, MD",
      publishedDate: "October 18, 2026",
      reachCount: 1390,
    },
  ],
  users: [
    {
      id: "usr-1",
      name: "Dr. Elena Ramos, MD",
      role: "Doctor",
      email: "tickeytikey01@gmail.com",
      phone: "0917-111-2233",
      purok: "Health Station Main",
      station: "Barangay San Antonio Health Station",
      status: "Active",
      lastActive: "Just now",
      avatar: "/assets/doctor.webp",
      licenseNumber: "PRC-0114892",
      philHealthId: "PH-12-0048192-1",
      assignedCasesCount: 14,
      joinedDate: "January 15, 2024",
    },
    {
      id: "usr-2",
      name: "Carmela Perez, RN",
      role: "Nurse",
      email: "tickeytikey01@gmail.com",
      phone: "0918-222-3344",
      purok: "Health Station Main",
      station: "Barangay San Antonio Health Station",
      status: "Active",
      lastActive: "15 mins ago",
      avatar: "/assets/female-doctor.webp",
      licenseNumber: "PRC-0089124",
      philHealthId: "PH-12-0099412-3",
      assignedCasesCount: 8,
      joinedDate: "March 1, 2024",
    },
    {
      id: "usr-3",
      name: "May Castro, RM",
      role: "Nurse",
      email: "tickeytikey01@gmail.com",
      phone: "0919-333-4455",
      purok: "Maternal Health Unit",
      station: "Barangay San Antonio Health Station",
      status: "Active",
      lastActive: "30 mins ago",
      avatar: "/assets/female-doctor.webp",
      licenseNumber: "PRC-0044129",
      philHealthId: "PH-12-0088192-5",
      assignedCasesCount: 6,
      joinedDate: "April 10, 2024",
    },
    {
      id: "usr-4",
      name: "Ana Reyes",
      role: "BHW",
      email: "tickeytikey01@gmail.com",
      phone: "0928-123-4567",
      purok: "Purok 2",
      station: "Barangay San Antonio Health Station",
      status: "Active",
      lastActive: "5 mins ago",
      avatar: "/assets/female-doctor.webp",
      assignedCasesCount: 12,
      joinedDate: "June 20, 2024",
    },
    {
      id: "usr-5",
      name: "Marites Dela Cruz",
      role: "BHW",
      email: "tickeytikey01@gmail.com",
      phone: "0919-444-1122",
      purok: "Purok 1",
      station: "Barangay San Antonio Health Station",
      status: "Active",
      lastActive: "1 hour ago",
      avatar: "/assets/female-doctor.webp",
      assignedCasesCount: 10,
      joinedDate: "June 20, 2024",
    },
    {
      id: "usr-6",
      name: "TickyTICKEY ICT Admin",
      role: "Admin",
      email: "tickeytikey01@gmail.com",
      phone: "0920-555-6677",
      purok: "Barangay Hall ICT",
      station: "Barangay San Antonio ICT Desk",
      status: "Active",
      lastActive: "10 mins ago",
      avatar: "/assets/man.webp",
      assignedCasesCount: 0,
      joinedDate: "January 10, 2024",
    },
    {
      id: "usr-7",
      name: "Maria Santos",
      role: "Resident",
      email: "maria.santos.sanantonio@gmail.com",
      phone: "0917-123-4567",
      purok: "Purok 2",
      station: "Barangay San Antonio",
      status: "Active",
      lastActive: "10 mins ago",
      avatar: "/assets/female-user.webp",
      philHealthId: "12-345678901-2",
      assignedCasesCount: 1,
      joinedDate: "July 12, 2024",
    },
    {
      id: "usr-8",
      name: "Juan Dela Cruz",
      role: "Resident",
      email: "juan.delacruz.sanantonio@gmail.com",
      phone: "0920-555-7890",
      purok: "Purok 1",
      station: "Barangay San Antonio",
      status: "Active",
      lastActive: "25 mins ago",
      avatar: "/assets/man.webp",
      philHealthId: "09-876543210-9",
      assignedCasesCount: 1,
      joinedDate: "August 4, 2024",
    },
  ],
  healthRecords: [
    {
      id: "rec-1",
      residentName: "Maria Santos",
      initials: "MS",
      age: 34,
      gender: "Female",
      bloodType: "O+",
      purok: "Purok 2",
      philHealthId: "12-345678901-2",
      residentId: "RES-2026-0042",
      contactPhone: "0917-123-4567",
      emergencyContact: {
        name: "Carlos Santos",
        relationship: "Spouse",
        phone: "0918-333-2211",
      },
      chronicConditions: ["Mild Bronchial Asthma"],
      allergies: ["Penicillin", "Dust Mites"],
      vitals: {
        bp: "118/76 mmHg",
        heartRate: "78 bpm",
        temp: "38.8 °C",
        weight: "56 kg",
        height: "158 cm",
        bmi: "22.4",
        bloodSugar: "92 mg/dL",
        lastUpdated: "Today, 09:30 AM",
      },
      primaryCategory: "General",
      assignedBhw: "Ana Reyes (BHW)",
      status: "Active",
      lastVisitDate: "October 24, 2026",
      prescriptions: [
        {
          id: "rx-1",
          medicineName: "Paracetamol 500mg",
          dosage: "1 tablet",
          frequency: "Every 4 hours PRN",
          duration: "3 days",
          prescribedBy: "Dr. Elena Ramos, MD",
          status: "Active",
        },
        {
          id: "rx-2",
          medicineName: "Salbutamol Inhaler 100mcg",
          dosage: "2 puffs",
          frequency: "As needed for wheezing",
          duration: "Maintenance",
          prescribedBy: "Dr. Elena Ramos, MD",
          status: "Active",
        },
      ],
      vaccinations: [
        {
          id: "vac-1",
          vaccineName: "COVID-19 Bivalent Booster",
          dose: "Booster Dose",
          dateAdministered: "Nov 14, 2025",
          healthcareProvider: "Pasig City Health Dept",
        },
        {
          id: "vac-2",
          vaccineName: "Influenza Quadrivalent",
          dose: "Annual Dose",
          dateAdministered: "Oct 12, 2025",
          healthcareProvider: "San Antonio Clinic",
        },
      ],
      clinicalNotes: [
        {
          id: "note-1",
          date: "Oct 24, 2026",
          author: "Dr. Elena Ramos, MD",
          role: "Physician",
          note: "Patient presented with 3-day history of fever (38.8°C) and non-productive cough. Lungs clear to auscultation, no wheezing. Advised oral hydration, Paracetamol, and home rest.",
        },
      ],
    },
    {
      id: "rec-2",
      residentName: "Juan Dela Cruz",
      initials: "JD",
      age: 58,
      gender: "Male",
      bloodType: "A+",
      purok: "Purok 1",
      philHealthId: "09-876543210-9",
      residentId: "RES-2026-0089",
      contactPhone: "0920-555-7890",
      emergencyContact: {
        name: "Luzviminda Dela Cruz",
        relationship: "Spouse",
        phone: "0919-444-5566",
      },
      chronicConditions: ["Stage 2 Essential Hypertension"],
      allergies: ["None known"],
      vitals: {
        bp: "150/95 mmHg",
        heartRate: "84 bpm",
        temp: "36.7 °C",
        weight: "74 kg",
        height: "168 cm",
        bmi: "26.2",
        bloodSugar: "105 mg/dL",
        lastUpdated: "Today, 09:15 AM",
      },
      primaryCategory: "Hypertension",
      assignedBhw: "Marites Dela Cruz (BHW)",
      status: "Active",
      lastVisitDate: "October 24, 2026",
      prescriptions: [
        {
          id: "rx-3",
          medicineName: "Losartan Potassium 50mg",
          dosage: "1 tablet",
          frequency: "Once daily morning",
          duration: "Long-term Maintenance",
          prescribedBy: "Dr. Elena Ramos, MD",
          status: "Active",
        },
        {
          id: "rx-4",
          medicineName: "Amlodipine Besylate 5mg",
          dosage: "1 tablet",
          frequency: "Once daily evening",
          duration: "Long-term Maintenance",
          prescribedBy: "Dr. Elena Ramos, MD",
          status: "Active",
        },
      ],
      vaccinations: [
        {
          id: "vac-3",
          vaccineName: "Pneumococcal Polysaccharide (PPSV23)",
          dose: "Single Dose",
          dateAdministered: "Aug 20, 2025",
          healthcareProvider: "San Antonio Clinic",
        },
      ],
      clinicalNotes: [
        {
          id: "note-2",
          date: "Oct 24, 2026",
          author: "Dr. Elena Ramos, MD",
          role: "Physician",
          note: "Elevated BP (150/95) noted after missed dose. Urged strict compliance with Losartan and daily morning BP log. Diet low-salt, low-fat counseling conducted.",
        },
      ],
    },
    {
      id: "rec-3",
      residentName: "Rosa Mendoza",
      initials: "RM",
      age: 28,
      gender: "Female",
      bloodType: "B+",
      purok: "Purok 3",
      philHealthId: "14-002948192-3",
      residentId: "RES-2026-0154",
      contactPhone: "0918-777-3321",
      emergencyContact: {
        name: "Eduardo Mendoza",
        relationship: "Spouse",
        phone: "0921-999-8877",
      },
      chronicConditions: ["None"],
      allergies: ["Shellfish / Seafood"],
      vitals: {
        bp: "110/72 mmHg",
        heartRate: "74 bpm",
        temp: "36.6 °C",
        weight: "52 kg",
        height: "155 cm",
        bmi: "21.6",
        lastUpdated: "Oct 20, 2026",
      },
      primaryCategory: "General",
      assignedBhw: "Ana Reyes (BHW)",
      status: "Active",
      lastVisitDate: "October 20, 2026",
      prescriptions: [
        {
          id: "rx-5",
          medicineName: "Cetirizine 10mg",
          dosage: "1 tablet",
          frequency: "Once daily PRN",
          duration: "5 days",
          prescribedBy: "Dr. Elena Ramos, MD",
          status: "Active",
        },
      ],
      vaccinations: [
        {
          id: "vac-4",
          vaccineName: "Tetanus Diphtheria (Td)",
          dose: "Booster",
          dateAdministered: "Feb 10, 2025",
          healthcareProvider: "San Antonio Clinic",
        },
      ],
      clinicalNotes: [
        {
          id: "note-3",
          date: "Oct 20, 2026",
          author: "Ana Reyes",
          role: "BHW",
          note: "Family health profile updated. Toddler Sofia's immunization passport on track.",
        },
      ],
    },
    {
      id: "rec-4",
      residentName: "Ricardo Gomez",
      initials: "RG",
      age: 64,
      gender: "Male",
      bloodType: "O+",
      purok: "Purok 4",
      philHealthId: "01-998822331-4",
      residentId: "RES-2026-0210",
      contactPhone: "0921-888-9900",
      emergencyContact: {
        name: "Rosalinda Gomez",
        relationship: "Daughter",
        phone: "0922-111-4433",
      },
      chronicConditions: ["Hypertension", "Dyslipidemia"],
      allergies: ["Aspirin"],
      vitals: {
        bp: "124/82 mmHg",
        heartRate: "72 bpm",
        temp: "36.5 °C",
        weight: "68 kg",
        height: "165 cm",
        bmi: "25.0",
        bloodSugar: "98 mg/dL",
        lastUpdated: "Oct 15, 2026",
      },
      primaryCategory: "Senior Care",
      assignedBhw: "Elena Cruz (BHW)",
      status: "Active",
      lastVisitDate: "October 15, 2026",
      prescriptions: [
        {
          id: "rx-6",
          medicineName: "Losartan 50mg",
          dosage: "1 tablet",
          frequency: "Once daily",
          duration: "Monthly refill",
          prescribedBy: "Dr. Elena Ramos, MD",
          status: "Active",
        },
        {
          id: "rx-7",
          medicineName: "Atorvastatin 20mg",
          dosage: "1 tablet",
          frequency: "Once daily at bedtime",
          duration: "Monthly refill",
          prescribedBy: "Dr. Elena Ramos, MD",
          status: "Active",
        },
      ],
      vaccinations: [
        {
          id: "vac-5",
          vaccineName: "Pneumococcal Conjugate (PCV13)",
          dose: "Complete",
          dateAdministered: "Sep 05, 2024",
          healthcareProvider: "San Antonio Clinic",
        },
      ],
      clinicalNotes: [
        {
          id: "note-4",
          date: "Oct 15, 2026",
          author: "Dr. Elena Ramos, MD",
          role: "Physician",
          note: "Well-controlled blood pressure on current medication regimen. Next laboratory lipids scheduled for December.",
        },
      ],
    },
    {
      id: "rec-5",
      residentName: "Teresa Aquino",
      initials: "TA",
      age: 26,
      gender: "Female",
      bloodType: "O+",
      purok: "Purok 2",
      philHealthId: "12-004499112-8",
      residentId: "RES-2026-0312",
      contactPhone: "0916-999-4455",
      emergencyContact: {
        name: "Mark Aquino",
        relationship: "Spouse",
        phone: "0917-888-9900",
      },
      chronicConditions: ["None"],
      allergies: ["None"],
      vitals: {
        bp: "114/74 mmHg",
        heartRate: "82 bpm",
        temp: "36.8 °C",
        weight: "62 kg",
        height: "160 cm",
        bmi: "24.2",
        lastUpdated: "Today, 07:45 AM",
      },
      primaryCategory: "Maternal/Prenatal",
      assignedBhw: "Midwife May Castro",
      status: "Active",
      lastVisitDate: "October 24, 2026",
      prescriptions: [
        {
          id: "rx-8",
          medicineName: "Ferrous Sulfate + Folic Acid",
          dosage: "1 tablet",
          frequency: "Once daily",
          duration: "Throughout pregnancy",
          prescribedBy: "Midwife May Castro",
          status: "Active",
        },
        {
          id: "rx-9",
          medicineName: "Calcium Carbonate 500mg",
          dosage: "1 tablet",
          frequency: "Once daily with lunch",
          duration: "Throughout pregnancy",
          prescribedBy: "Midwife May Castro",
          status: "Active",
        },
      ],
      vaccinations: [
        {
          id: "vac-6",
          vaccineName: "Tetanus Toxoid Booster (TT3)",
          dose: "Dose 3",
          dateAdministered: "Sep 15, 2026",
          healthcareProvider: "Midwife May Castro",
        },
      ],
      clinicalNotes: [
        {
          id: "note-5",
          date: "Oct 24, 2026",
          author: "Midwife May Castro",
          role: "Midwife",
          note: "32 weeks gestation. Fundic height 31cm, fetal heart tones 142 bpm regular. Cephalic presentation. Advised birth plan preparation.",
        },
      ],
    },
    {
      id: "rec-6",
      residentName: "Jose Bautista",
      initials: "JB",
      age: 42,
      gender: "Male",
      bloodType: "AB+",
      purok: "Purok 5",
      philHealthId: "08-774411992-1",
      residentId: "RES-2026-0401",
      contactPhone: "0927-444-1234",
      emergencyContact: {
        name: "Liza Bautista",
        relationship: "Spouse",
        phone: "0928-555-6677",
      },
      chronicConditions: ["GERD (Gastroesophageal Reflux)"],
      allergies: ["Ibuprofen"],
      vitals: {
        bp: "122/80 mmHg",
        heartRate: "76 bpm",
        temp: "36.6 °C",
        weight: "72 kg",
        height: "170 cm",
        bmi: "24.9",
        lastUpdated: "Today, 06:50 AM",
      },
      primaryCategory: "General",
      assignedBhw: "Ana Reyes (BHW)",
      status: "Active",
      lastVisitDate: "October 24, 2026",
      prescriptions: [
        {
          id: "rx-10",
          medicineName: "Aluminum Magnesium Hydroxide",
          dosage: "10 mL",
          frequency: "Post-prandial PRN",
          duration: "7 days",
          prescribedBy: "Dr. Elena Ramos, MD",
          status: "Active",
        },
      ],
      vaccinations: [
        {
          id: "vac-7",
          vaccineName: "Hepatitis B Recombinant",
          dose: "Complete Series (3 doses)",
          dateAdministered: "Jan 12, 2024",
          healthcareProvider: "Pasig City Health Dept",
        },
      ],
      clinicalNotes: [
        {
          id: "note-6",
          date: "Oct 24, 2026",
          author: "Ana Reyes",
          role: "BHW",
          note: "Symptoms resolved after oral antacid intake. Patient counseled on smoking cessation and meal timing.",
        },
      ],
    },
  ],
  settings: {
    clinic: {
      stationName: "Barangay San Antonio Health Station",
      barangay: "San Antonio",
      cityMunicipality: "Pasig City",
      province: "Metro Manila",
      headPhysician: "Dr. Elena Ramos, MD",
      contactNumber: "+63 (02) 8911-0000",
      emergencyHotline: "0928-765-4321",
      operatingDays: "Monday to Saturday",
      operatingHours: "08:00 AM - 05:00 PM",
      address: "Caruncho Complex, Barangay San Antonio, Pasig City, Metro Manila",
    },
    triage: {
      autoAssignBhws: true,
      telemedicineEnabled: true,
      maxCasesPerBhw: 15,
      urgentEscalationPhone: "0928-765-4321",
      responseTemplateFever: "Magandang araw. Uminom ng Paracetamol kada 4-6 oras at i-monitor ang inyong temperatura. Mag-update muli pagkalipas ng 2 oras.",
      responseTemplateCough: "Magandang araw. Uminom ng maraming maligamgam na tubig at magpahinga. Magsuot ng facemask upang maprotektahan ang pamilya.",
    },
    notifications: {
      smsGatewayProvider: "Semaphore",
      smsApiKey: "demo_semaphore_key_sanantonio",
      smsSenderName: "TickyTICKEY",
      enableResidentSmsAlerts: true,
      lowStockThresholdPcs: 25,
      enableDailyDigestEmail: true,
      digestRecipientEmail: "tickeytikey01@gmail.com",
    },
    security: {
      sessionTimeoutMinutes: 30,
      requireTwoFactorAuth: false,
      strictPasswordPolicy: true,
      dataPrivacyNoticeVersion: "2026.1 (RA 10173)",
      auditLoggingEnabled: true,
    },
  },
  permissions: [
    "users.manage",
    "announcements.manage",
    "settings.manage",
    "medicines.manage",
    "records.manage",
  ],
};
